export const food_menu_item = [
    {
        image: "BabyCorn_Ghee_Roast.jpg",
        name: "BabyCorn Ghee Roast",
        description: "A Spicy and Popular Dish usually found in the Coastal Regions of Karnataka, India. Baby Corn cooked in a Gravy made of Dry Roasted Spices and garlic blend into a smooth paste.",
        price: "$10",
        isDeleted: false,
        category:"Main Course",
        cuisine: "Indian",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "Baby Corn, Ghee, Red Chillies, Garlic, Cinnamon, Fenugreek Seeds, Cumin Seeds, Coriander Seeds, Tamamrind Paste, Curd(Yogurt), Lemon Juice, Turmeric Powder, Chilli Powder "
    },
    {
        image: "Scotch_Eggs.jpg",
        name: "Scotch Eggs",
        description: "A traditional British Dish containg a Hard-Boiled Egg wrapped in Meat(Chicken/Pork) and covered in breadcrumbs to be fried/baked.",
        price: "$15",
        isDeleted: false,
        category:"Main Course",
        cuisine: "British",
        preference: "Non-Vegetarian",
        stockQuantity: 150,
        ingredients: "Pork/Chicken, Onions, Eggs, Bread Crumbs, Oil(if frying)"
    },
    {
        image: "Denver_Omelet.jpg",
        name: "Denver Omelet",
        description: "Classic Diner Order served with a side of Hash Browns or Toast. Has a firmer texture and a more caramelized flavor compared to a classic French Omelet ",
        price: "$20",
        isDeleted: false,
        category:"Appetizer",
        cuisine: "American",
        preference: "Non-Vegetarian",
        stockQuantity: 125,
        ingredients: "Sausages(Chicken/Pork), Eggs, Green Bell Pepper, Cheddar Cheese, Pepper, Onions, Oil"
    },
    {
        image: "Vanilla_Panna_Cotta.jpg",
        name: "Vanilla Panna Cotta with Chocolate Sauce",
        description: "A 'chilled' Italian Dessert. Silky Smooth Eggless Custard that literally means Cooked Cream. Served with a Drizzle of Chocolate Syrup.",
        price: "$23",
        isDeleted: false,
        category:"Dessert",
        cuisine: "Italian",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "Milk, Cream, Gelatin, Sugar, Vanilla Extract, Chocolate Syrup"
    },
    {
        image: "Chicken_Schnitzel.jpg",
        name: "Chicken Schnitzel",
        description: "Traditional German Dish. Pounded Meat(Chicken) coated with Egg Wash and Breadcrumbs mixed with Seasonings",
        price: "$30",
        isDeleted: false,
        category:"Main Course",
        cuisine: "German",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "Chicken Breast, Pepper, Chilli Powder, Rosemary, Thyme, Cornflour, Eggs, Breadcrumbs"
    },
    {
        image: "Palak_Paneer.jpg",
        name: "Palak Paneer",
        description: "Classical North Indian Dish made with succulent Cottage Cheese Cubes cooked in a Smooth Spinach Gravy",
        price: "$30",
        isDeleted: false,
        category:"Main Course",
        cuisine: "Indian",
        preference: "Vegetarian",
        stockQuantity: 120,
        ingredients: "Cottage Cheese, Onions, Spinach, Garlic, Cream"
    },
    {
        image: "Turkish_Poached_Eggs.jpg",
        name: "Turkish Poached Eggs (Cilbir)",
        description: "Traditional Mediterranean Dish. Perfectly Poached Eggs served over a Garlicky Yogurt, and finished with a warm Spicy Butter or Olive Oil",
        price: "$30",
        isDeleted: false,
        category:"Main Course",
        cuisine: "Mediterranean",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "Eggs, Garlic, Butter, Yogurt(Curd), Oil, Red Chilli Oil, Water for Poaching"
    },
    {
        image: "Omurice.jpg",
        name: "Omurice",
        description: "Contemporary Japanese Fusion Creation blending the Western Omelet and Japanese Fried Rice",
        price: "$30",
        isDeleted: false,
        category:"Main Course",
        cuisine: "Japanese",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "Rice, Bell Pepper, Eggs, Oil, Soy Sauce, Spring Onions"
    },
    {
        image: "Paneer_Tikka.jpg",
        name: "Paneer Tikka",
        description: "Popular Tandoor Based Snack. Marinated in a Spiced Yogurt, kept on Skewers and Grilled in an Oven.",
        price: "$18",
        isDeleted: false,
        category:"Appetizer",
        cuisine: "Indian",
        preference: "Vegetarian",
        stockQuantity: 110,
        ingredients: "Cottage Cheese, Yogurt(Curd), Pesto Sauce, Red Chilli Powder, Pepper, Rosemary, Thyme, Oil, Garlic"
    },
    {
        image: "Vanilla_Banana_Parfait.jpg",
        name: "Vanilla Banana Parfait",
        description: "Parfait meaning Perfect - Dessert with Multiple Textures - Smooth from the Parfait, Crumbly from the Crackers and Wafers and Fruity from the Bananas.",
        price: "$15",
        isDeleted: false,
        category:"Dessert",
        cuisine: "French",
        preference: "Vegetarian",
        stockQuantity: 200,
        ingredients: "Milk, Cream, Vanilla Extract, Gelatin, Bananas, Vanilla Wafers, Sugar, Graham Cracker Crumbs"
    },
    {
        image: "Creamy_Mushroom_Pasta.jpg",
        name: "Creamy Mushroom Pasta",
        description: "A classic Italian Dish. Creamy flavor from the sauce and Umami Flavor from the Mushrooms gives the Perfect Harmony in your Mouth",
        price: "$22",
        isDeleted: false,
        category:"Main Course",
        cuisine: "Italian",
        preference: "Vegetarian",
        stockQuantity: 130,
        ingredients: "Fettucine Pasta, Mushrroms, Olives, All-Purpose Flour, Butter, Garlic, Parsley"
    },
    {
        image: "Custard_T_Cup.jpg",
        name: "Custard T-Cup",
        description: "Modern take on Ice Cream and Custard. Served in a Tea Cup",
        price: "$12",
        isDeleted: false,
        category:"Dessert",
        cuisine: "Modern",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "Milk, Vanilla Extract, Gelatin, Vanilla Ice-Cream, Sugar, Butter, Egg Whites, All-Purpose Flour"
    },
    {
        image: "Vegetable_Pizza.jpg",
        name: "Veggie Farmhouse Pizza",
        description: "A Simple many Veggies Pizza on a Medium Sized Soft Garlic flavored Crust.",
        price: "$25",
        isDeleted: false,
        category:"Main Course",
        cuisine: "Italian",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "All Purpose Flour, Butter, Yeast, Sugar, Oil, Garlic Powder, Mushrooms, Bell Peppers, Onions, Olives"
    },
]


export const drinks_menu_item = [
    {
        image: "item1.jpg",
        name: "Item 1",
        description: "Item Description",
        price: "$10",
        isDeleted: false,
        category:"Category 1",
        level: "level 1",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item2.jpg",
        name: "Item 2",
        description: "Item Description",
        price: "$15",
        isDeleted: false,
        category:"Category 2",
        level: "level 4",
        stockQuantity: 150,
        ingredients: "a,c,d"
    },
    {
        image: "item3.jpg",
        name: "Item 3",
        description: "Item Description",
        price: "$20",
        isDeleted: false,
        category:"Category 2",
        level: "level 5",
        stockQuantity: 125,
        ingredients: "a,b,c,d"
    },
    {
        image: "item4.jpg",
        name: "Item 4",
        description: "Item Description",
        price: "$23",
        isDeleted: false,
        category:"Category 2",
        level: "level 3",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item6.jpg",
        name: "Item 6",
        description: "Item Description",
        price: "$18",
        isDeleted: false,
        category:"Category 5",
        level: "level 2",
        stockQuantity: 110,
        ingredients: "a,b,c,d"
    },
    {
        image: "item7.jpg",
        name: "Item 7",
        description: "Item Description",
        price: "$15",
        isDeleted: false,
        category:"Category 7",
        level: "level 6",
        stockQuantity: 200,
        ingredients: "a,b,c,d"
    },
    {
        image: "item8.jpg",
        name: "Item 8",
        description: "Item Description",
        price: "$22",
        isDeleted: false,
        category:"Category 2",
        level: "level 5",
        stockQuantity: 130,
        ingredients: "a,b,c,d"
    },
    {
        image: "item9.jpg",
        name: "Item 9",
        description: "Item Description",
        price: "$12",
        isDeleted: false,
        category:"Category 3",
        level: "level 1",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item10.jpg",
        name: "Item 10",
        description: "Item Description",
        price: "$25",
        isDeleted: false,
        category:"Category 1",
        level: "level 4",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
]