export const food_menu_item = [
    {
        image: "item1.jpg",
        name: "Item 1",
        description: "Item Description",
        price: "$10",
        isDeleted: false,
        category:"Category 1",
        cuisine: "Cuisine 1",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item2.jpg",
        name: "Item 2",
        description: "Item Description",
        price: "$15",
        isDeleted: false,
        category:"Category 2",
        cuisine: "Cuisine 4",
        preference: "Non-Vegetarian",
        stockQuantity: 150,
        ingredients: "a,c,d"
    },
    {
        image: "item3.jpg",
        name: "Item 3",
        description: "Item Description",
        price: "$20",
        isDeleted: false,
        category:"Category 2",
        cuisine: "Cuisine 5",
        preference: "Vegetarian",
        stockQuantity: 125,
        ingredients: "a,b,c,d"
    },
    {
        image: "item4.jpg",
        name: "Item 4",
        description: "Item Description",
        price: "$23",
        isDeleted: false,
        category:"Category 2",
        cuisine: "Cuisine 3",
        preference: "Non-Vegetarian",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        cuisine: "Cuisine 6",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        cuisine: "Cuisine 6",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        cuisine: "Cuisine 6",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        cuisine: "Cuisine 6",
        preference: "Non-Vegetarian",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item6.jpg",
        name: "Item 6",
        description: "Item Description",
        price: "$18",
        isDeleted: false,
        category:"Category 5",
        cuisine: "Cuisine 2",
        preference: "Vegetarian",
        stockQuantity: 110,
        ingredients: "a,b,c,d"
    },
    {
        image: "item7.jpg",
        name: "Item 7",
        description: "Item Description",
        price: "$15",
        isDeleted: false,
        category:"Category 7",
        cuisine: "Cuisine 6",
        preference: "Vegetarian",
        stockQuantity: 200,
        ingredients: "a,b,c,d"
    },
    {
        image: "item8.jpg",
        name: "Item 8",
        description: "Item Description",
        price: "$22",
        isDeleted: false,
        category:"Category 2",
        cuisine: "Cuisine 5",
        preference: "Non-Vegetarian",
        stockQuantity: 130,
        ingredients: "a,b,c,d"
    },
    {
        image: "item9.jpg",
        name: "Item 9",
        description: "Item Description",
        price: "$12",
        isDeleted: false,
        category:"Category 3",
        cuisine: "Cuisine 1",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item10.jpg",
        name: "Item 10",
        description: "Item Description",
        price: "$25",
        isDeleted: false,
        category:"Category 1",
        cuisine: "Cuisine 4",
        preference: "Vegetarian",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
]


export const drinks_menu_item = [
    {
        image: "item1.jpg",
        name: "Item 1",
        description: "Item Description",
        price: "$10",
        isDeleted: false,
        category:"Category 1",
        level: "level 1",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item2.jpg",
        name: "Item 2",
        description: "Item Description",
        price: "$15",
        isDeleted: false,
        category:"Category 2",
        level: "level 4",
        stockQuantity: 150,
        ingredients: "a,c,d"
    },
    {
        image: "item3.jpg",
        name: "Item 3",
        description: "Item Description",
        price: "$20",
        isDeleted: false,
        category:"Category 2",
        level: "level 5",
        stockQuantity: 125,
        ingredients: "a,b,c,d"
    },
    {
        image: "item4.jpg",
        name: "Item 4",
        description: "Item Description",
        price: "$23",
        isDeleted: false,
        category:"Category 2",
        level: "level 3",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item5.jpg",
        name: "Item 5",
        description: "Item Description",
        price: "$30",
        isDeleted: false,
        category:"Category 1",
        level: "level 6",
        stockQuantity: 120,
        ingredients: "a,b,c,d"
    },
    {
        image: "item6.jpg",
        name: "Item 6",
        description: "Item Description",
        price: "$18",
        isDeleted: false,
        category:"Category 5",
        level: "level 2",
        stockQuantity: 110,
        ingredients: "a,b,c,d"
    },
    {
        image: "item7.jpg",
        name: "Item 7",
        description: "Item Description",
        price: "$15",
        isDeleted: false,
        category:"Category 7",
        level: "level 6",
        stockQuantity: 200,
        ingredients: "a,b,c,d"
    },
    {
        image: "item8.jpg",
        name: "Item 8",
        description: "Item Description",
        price: "$22",
        isDeleted: false,
        category:"Category 2",
        level: "level 5",
        stockQuantity: 130,
        ingredients: "a,b,c,d"
    },
    {
        image: "item9.jpg",
        name: "Item 9",
        description: "Item Description",
        price: "$12",
        isDeleted: false,
        category:"Category 3",
        level: "level 1",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
    {
        image: "item10.jpg",
        name: "Item 10",
        description: "Item Description",
        price: "$25",
        isDeleted: false,
        category:"Category 1",
        level: "level 4",
        stockQuantity: 100,
        ingredients: "a,b,c,d"
    },
]